# -*- coding: utf-8 -*-
"""streamlit01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ACrrcL10FNCFm1vVdMMIw24QO4cKp1xm
"""

import streamlit as st
st.title('챗봇 테스트xxx')


prompt = st.chat_input("Say something")
if prompt:
    st.write(f"User has sent the following prompt: {prompt}")
